Gezichteninborden
geensnor/geensnor.nl-oud pull request #11
Opened 2021-04-05 20:08 UTC by Zuijdam

Lightbox: https://jekyllcodex.org/without-plugin/lightbox/
gallery: https://jekyllcodex.org/without-plugin/image-gallery/
en een zwik gezichten in borden.

Ook de default.layout aangepast

2021-04-05 20:28 UTC, reithose requested changes
Denk dat de pagina niet in het dropdown menu moet. Drop down is meer voor pagina's deze site.

2021-04-05 20:31 UTC, Zuijdam commented
Eens, aangepast

2021-04-05 20:32 UTC, reithose requested changes
Kunnen de CSS en JS niet alleen in de pagina worden include waarin ze ook echt worden gebruikt? De default.html is wel erg......default.....

2021-04-05 20:35 UTC, reithose approved these changes

2021-04-05 20:35 UTC, Zuijdam commented
Nou daar dacht ik even over maar besloot toen dat heel geensnor er van kan profiteren. Alle posts kunnen nu gebruik maken van de lightbox voor images, en dat is wel zo fraai imho. Dat gaat trouwens vol autoamtisch bij elke link naar een jpg.

2021-04-05 20:39 UTC, reithose commented
> Nou daar dacht ik even over maar besloot toen dat heel geensnor er van kan profiteren. Alle posts kunnen nu gebruik maken van de lightbox voor images, en dat is wel zo fraai imho. Dat gaat trouwens vol autoamtisch bij elke link naar een jpg.

Maar als je de JS en CSS voor de Lightbox uit default.html haalt en in de image-gallery.html zet? Dan kun je hem toch ook overal gebruiken?

2021-04-05 21:04 UTC, Zuijdam commented
Nou dan kijk ik daar morgen nog eens naar. Lig nu in bed

2021-04-05 21:05 UTC, Zuijdam commented
> > Nou daar dacht ik even over maar besloot toen dat heel geensnor er van kan profiteren. Alle posts kunnen nu gebruik maken van de lightbox voor images, en dat is wel zo fraai imho. Dat gaat trouwens vol autoamtisch bij elke link naar een jpg.
> 
> 
> 
> Maar als je de JS en CSS voor de Lightbox uit default.html haalt en in de image-gallery.html zet? Dan kun je hem toch ook overal gebruiken?

Nee. Alleen als je een gallery gebruikt. Maar als je in een post ook een lightbox wil van 1 plaatje of video, moet ie in default toch?

2021-04-06 11:12 UTC, reithose commented
> > > Nou daar dacht ik even over maar besloot toen dat heel geensnor er van kan profiteren. Alle posts kunnen nu gebruik maken van de lightbox voor images, en dat is wel zo fraai imho. Dat gaat trouwens vol autoamtisch bij elke link naar een jpg.
> > 
> > 
> > Maar als je de JS en CSS voor de Lightbox uit default.html haalt en in de image-gallery.html zet? Dan kun je hem toch ook overal gebruiken?
> 
> Nee. Alleen als je een gallery gebruikt. Maar als je in een post ook een lightbox wil van 1 plaatje of video, moet ie in default toch? Of maw. die lightbox functionaliteit is altijd handig, niet alleen in de context van een gallery maar ook in losse posts/afbeeldingen.

Oke, maar dan is het misschien meer iets voor de head.

2021-04-06 11:18 UTC, Zuijdam commented
Of air enough. Het is naar de head verplaatst

2021-04-06 11:24 UTC, reithose approved these changes

2021-04-06 11:25 UTC, merged